# Generated by Django 5.2.13 on 2026-04-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_ride_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10),
        ),
    ]
