# Generated by Django 5.2.13 on 2026-04-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_ride_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ride',
            name='drop',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
