# Generated by Django 5.2.13 on 2026-04-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_ride_payment_status_ride_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='drop',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
